### ISSUE TITLE
Create Code Spaces

### ISSUE THREAD

**Issue by joelzamboni** [wearewebera/openvela#15]
Since we are slowly open-sourcing our internal agents' platform, ideally, we would have other contributors, and we believe it would be nice to have the GitHub Codespaces feature enabled to facilitate the integration of new team members.

**Comment by samuel-patrocinio** [comment]
I added the devcontainer code under `.devcontainer`. Already created a realease `v0.1.3` on pipy.

**Comment by samuel-patrocinio** [comment]
@joelzamboni If we want to set up codespaces we have to set up who pays.

This page provides details:
https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/choosing-who-owns-and-pays-for-codespaces-in-your-organization

I'm not an owner of wearewebera, so I can't set this up. You can give me permissions to do so or set up yourself

**Comment by mauriciopeixoto3** [comment]
@joelzamboni fyi

**Comment by mauriciopeixoto3** [comment]
@joelzamboni can you review both codespaces tasks?

**Comment by NathaliaGS** [comment]
@joelzamboni  can you please review?

**Comment by joelzamboni** [comment]
I would love to see if @augustoizepon thinks of it, since he has been using it more recently
