### ISSUE TITLE
Improve OpenVela Deployment to Follow Webera Flow

### ISSUE THREAD

**Issue by mauriciopeixoto3** [wearewebera/openvela#28]
**Description:**
The current deployment process for OpenVela needs to be enhanced to align with the standard Webera flow. This task involves reviewing and adjusting the deployment steps to improve efficiency, consistency, and integration with the Webera workflow.

**Scope of Work:**
- Analyze the existing OpenVela deployment process.
- Implement adjustments to follow the deployment practices and standards established in Webera.
- Document the updated deployment steps to ensure alignment and repeatability.

**Acceptance Criteria:**
- OpenVela deployment process is updated to match the Webera flow.
- Documentation is complete and provides clear steps aligned with Webera standards.
- Deployment is tested and verified for consistency with the Webera workflow.

**Comment by samuel-patrocinio** [comment]
Refactored the action code and now it follows webera flow. @augustoizepon already tested it by making a release
